### ISSUE TITLE
Quick way to get indoor results ?

### ISSUE THREAD

**Issue by cigone-openindoor** [mdiener21/python-geospatial-analysis-cookbook#9]
Very very nice job !

Would you suggest an easier and quicker way to find shortest indoor path relying on the following context ?

* input: .osm / .geojson data
* output: geojson feature LineString

... Knowing that we could have stairs, escalators, elevator, doors, etc...

**Comment by mdiener21** [comment]
Input   .osm / .geojson   has issues since the quality cannot be guaranteed to work for routing.  There are alot of tools out there that clean OSM data for routing (outdoors).  Indoor routing with OSM is another level of difficulty in data management and analysis.  

Outputing GeoJSON is already part of the INDRZ api's.

The biggest issue as always remains the "data".  Where to get it and how to process it are the key ingredients to make an indoor routing application work.
